{
 "title": "Fabric1.4",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS_average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s])"
    }
   ]
  },
  {
   "title": "ARD_average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Tx_ARD<2" }
   ]
  },
  {
   "title": "TPC_average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s]) ) /sum( increase(container_cpu_usage_seconds_total{name=\"orderer.example.com\"}[5s])*2.5 )"
    }
   ]
  },
  {
   "title": "TPMS_average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s]) )/sum( sum( increase(container_memory_usage_bytes{name=\"orderer.example.com\"}[5s]) )/2+sum(container_memory_usage_bytes{name=\"orderer.example.com\"})  )*1024*1024/5"
    }
   ]
  },
  {
   "title": "TPN_average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s]) )/sum( increase(container_network_receive_bytes_total{name=\"orderer.example.com\"}[5s])+increase(container_network_transmit_bytes_total{name=\"orderer.example.com\"}[5s])  ) *1024"
    }
   ]
  },
  {
   "title": "TPDIO_average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s])) / (sum(increase(container_fs_reads_bytes_total{name=\"orderer.example.com\"}[5s]))+sum(increase(container_fs_writes_bytes_total{name=\"orderer.example.com\"}[5s])) )*1024"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s])"
    }
   ]
  },
  {
   "title": "ARD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Tx_Duration_bucket" }
   ]
  },
  {
   "title": "TPC(TxsGHz*s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s]) ) /sum( increase(container_cpu_usage_seconds_total{name=\"orderer.example.com\"}[5s])*2.5 )"
    }
   ]
  },
  {
   "title": "TPMS (Txs/MB*s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s]) )/sum( sum( increase(container_memory_usage_bytes{name=\"orderer.example.com\"}[5s]) )/2+sum(container_memory_usage_bytes{name=\"orderer.example.com\"})  )*1024*1024/5"
    }
   ]
  },
  {
   "title": "TPN(Txs/KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s]) )/sum( increase(container_network_receive_bytes_total{name=\"orderer.example.com\"}[5s])+increase(container_network_transmit_bytes_total{name=\"orderer.example.com\"}[5s])  ) *1024"
    }
   ]
  },
  {
   "title": "TPDIO(Txs/KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(broadcast_processed_count{channel=\"mychannel\",status=\"SUCCESS\",type=\"ENDORSER_TRANSACTION\"}[5s])) / (sum(increase(container_fs_reads_bytes_total{name=\"orderer.example.com\"}[5s]))+sum(increase(container_fs_writes_bytes_total{name=\"orderer.example.com\"}[5s])) )*1024"
    }
   ]
  }
 ]
}