{
 "title": "IOTA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TPS_avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(iota_zmq_seen_tx_count[1m]))"
    }
   ]
  },
  {
   "title": "Delay_avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(iota_zmq_tx_confirm_time_sum[1m]))/sum(rate(iota_zmq_tx_confirm_time_count[1m])) )"
    }
   ]
  },
  {
   "title": "TPC_avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(iota_zmq_seen_tx_count[1m]))/sum(increase(container_cpu_usage_seconds_total{image=\"iotaledger/iri:latest\"}[1m]))/2.5"
    }
   ]
  },
  {
   "title": "TPMS_avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(iota_zmq_seen_tx_count[1m]))/ sum( rate(container_memory_usage_bytes{image=~\"iota.+\"}[1m])*30+container_memory_usage_bytes{image=~\"iota.+\"}offset 60s ) *1024*1024/60"
    }
   ]
  },
  {
   "title": "TPN_avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(iota_zmq_seen_tx_count[1m]))/   sum(increase(container_network_transmit_bytes_total{image=~\"iota.+\"}[1m])+increase(container_network_receive_bytes_total{image=~\"iota.+\"}[1m])) *1024"
    }
   ]
  },
  {
   "title": "TPDIO_avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(iota_zmq_seen_tx_count[1m]))/  (sum(increase(node_disk_read_bytes_total[1m]))+sum(increase(node_disk_written_bytes_total[1m])) ) *1024"
    }
   ]
  },
  {
   "title": "Total Neighbors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "iota_node_info_total_neighbors" }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(iota_zmq_seen_tx_count[1m]))"
    }
   ]
  },
  {
   "title": "Confirm_Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iota_zmq_tx_confirm_time_bucket"
    }
   ]
  },
  {
   "title": "Active Neighbors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iota_neighbors_active_neighbors"
    }
   ]
  },
  {
   "title": "LMI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iota_node_info_latest_milestone"
    }
   ]
  },
  {
   "title": "TPC (Txs/GHz*s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(iota_zmq_seen_tx_count[1m]))/sum(increase(container_cpu_usage_seconds_total{image=\"iotaledger/iri:latest\"}[1m]))/2.5"
    }
   ]
  },
  {
   "title": "TPMS (Txs/MB*s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(iota_zmq_seen_tx_count[1m]))/ sum( rate(container_memory_usage_bytes{image=~\"iota.+\"}[1m])*30+container_memory_usage_bytes{image=~\"iota.+\"}offset 30s ) *1024*1024/60"
    }
   ]
  },
  {
   "title": "LSMI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iota_node_info_latest_subtangle_milestone"
    }
   ]
  },
  {
   "title": "OpenTxs (Tips)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_info_total_tips" }
   ]
  },
  {
   "title": "TPN (Txs/KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(iota_zmq_seen_tx_count[1m]))/   sum(increase(container_network_transmit_bytes_total{image=~\"iota.+\"}[1m])+increase(container_network_receive_bytes_total{image=~\"iota.+\"}[1m])) *1024"
    }
   ]
  },
  {
   "title": "TPDIO(Txs/KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(iota_zmq_seen_tx_count[1m]))/  (sum(increase(node_disk_read_bytes_total[1m]))+sum(increase(node_disk_written_bytes_total[1m])) ) *1024"
    }
   ]
  }
 ]
}